[theme]
primaryColor = "#E50914"                # Netflix-inspired red
backgroundColor = "#121212"             # Dark mode background
secondaryBackgroundColor = "#303030"    # Lighter gray for contrast
textColor = "#FFFFFF"                   # White text for readability
font = "sans serif"                     # Simple and modern font
